version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///./app.db
      - REDIS_HOST=redis
      - AWS_CONFIG_FILE=/root/.aws/config
      - AWS_SHARED_CREDENTIALS_FILE=/root/.aws/credentials
      - AWS_PROFILE=rnd
      - USER=root
      - HOME=/root
      # Remove explicit AWS credentials to use profile
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - /app/__pycache__
      - ./.env:/app/.env
      - ~/.aws:/root/.aws:ro
      # Create persistent volume for Amazon Q authentication
      - amazonq_auth:/root/.config/amazon-q
      - amazonq_local:/root/.local/share/amazon-q
    
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    env_file:
      - .env
    depends_on:
      - backend
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  amazonq_auth:
  amazonq_local:
